version: '3'
services:

  onos:
    build: base/onos
    environment:
        - ONOS_APPS=models.common,yang-gui
    env_file:
      - "onos.env"
    ports:
        -   8181:8181
    networks:
        sdn_control:
            ipv4_address: 10.100.3.204
  netopeer:
    build: base/netopeer
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      - NETCONF_USER=root
      - NETCONF_PASSWORD=root
      - SDN_NET=10.100.3.0/24
    env_file:
      - "onos.env"
    depends_on:
      - "onos"
    networks:
      - sdn_control
      - sdn_data

networks:
  sdn_control:
    driver: bridge
    ipam:
     config:
       - subnet: 10.100.3.0/24
    driver_opts:
     com.docker.network.bridge.name: sdn_control
  sdn_data:
    driver: bridge
    ipam:
     config:
       - subnet: 192.169.0.0/24
    driver_opts:
     com.docker.network.bridge.name: sdn_data
