version: '3'
services:

# Org1 #####################################

  onos:
    build: base/onos
    environment:
        - ONOS_APPS=fwd,netconf,drivers.netconf,netconfsb,yang-gui
    env_file:
      - ".env"
    ports:
        -   8181:8181
    networks:
        net_sdn:
            ipv4_address: 10.0.3.204

  # mininet:
  #   build: base/mininet
  #   container_name: mininet
  #   privileged: true
  #   depends_on:
  #       - "onos"
  #   links:
  #    - onos
  #    - netopeer
  #   environment:
  #    - DISPLAY
  #   volumes:
  #    - /tmp/.X11-unix:/tmp/.X11-unix
  #    - /lib/modules:/lib/modules
  #    - ./base/mininet/conf:/root/tfg
  #   networks:
  #     - red1

  netopeer:
    build: base/netopeer
    cap_add:
      - SYS_ADMIN
      - NET_ADMIN
    environment:
      - NETCONF_USER=root
      - NETCONF_PASSWORD=root
    env_file:
      - ".env"
    depends_on:
      - "onos"
    networks:
      - net_sdn




networks:
  net_sdn:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.3.0/24
